app:
   name: Spring Config from Repo Server
   welcome:
      message: Welcome to ${app.name}
   list: one,two,three, four
   map: "{connection: 'pdp', user: 'pdp01', password: 'pdp01_st'}"

db:
   connection: connection from config server
   host: localhost
   port: 5080
